using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace exception_handling_ex2__try_catch_finally__divide_by_zero
{
    internal class Program
    {
        static void Main(string[] args)
        {
            int n1 = 2;
            int n2 = 0;
            int res = 0;
            try
            {
                res = n1 / n2;
            }
            catch(Exception ee) //code will execute only if run time error occurs
            {
                Console.WriteLine("catch block is executing");
                Console.WriteLine(ee.ToString());
            }
            finally //code will execute whether error occurs or not
            {
                Console.WriteLine("finally block is executing");
                Console.WriteLine("res=" + res);
            }
            Console.WriteLine("bye");
            Console.ReadLine();

        }
    }
}
